K22CNT4-TTCD-Nguyễn Văn Hiếu-2210900102/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using K22CNT4_TTCD_Nguyễn_Văn_Hiếu_2210900102.Models;

namespace K22CNT4_TTCD_Nguyễn_Văn_Hiếu_2210900102.Controllers
{
    public class AdminController : Controller
    {
        private QLCHEntities1 db = new QLCHEntities1();

        // GET: Admin
        public ActionResult Index()
        {
            return View(db.QUAN_TRI.ToList());
        }

        // GET: Admin/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QUAN_TRI qUAN_TRI = db.QUAN_TRI.Find(id);
            if (qUAN_TRI == null)
            {
                return HttpNotFound();
            }
            return View(qUAN_TRI);
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "admin_username,admin_pass,admin_status")] QUAN_TRI qUAN_TRI)
        {
            if (ModelState.IsValid)
            {
                db.QUAN_TRI.Add(qUAN_TRI);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(qUAN_TRI);
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QUAN_TRI qUAN_TRI = db.QUAN_TRI.Find(id);
            if (qUAN_TRI == null)
            {
                return HttpNotFound();
            }
            return View(qUAN_TRI);
        }

        // POST: Admin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "admin_username,admin_pass,admin_status")] QUAN_TRI qUAN_TRI)
        {
            if (ModelState.IsValid)
            {
                db.Entry(qUAN_TRI).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(qUAN_TRI);
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QUAN_TRI qUAN_TRI = db.QUAN_TRI.Find(id);
            if (qUAN_TRI == null)
            {
                return HttpNotFound();
            }
            return View(qUAN_TRI);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            QUAN_TRI qUAN_TRI = db.QUAN_TRI.Find(id);
            db.QUAN_TRI.Remove(qUAN_TRI);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        // GET: PRODUCTs
        public ActionResult AdProIndex()
        {
            return View(db.PRODUCTs.ToList());
        }
        public ActionResult AdProDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PRODUCT pRODUCT = db.PRODUCTs.Find(id);
            if (pRODUCT == null)
            {
                return HttpNotFound();
            }
            return View(pRODUCT);
        }
        // GET: Product/Create
        public ActionResult AdProCreate()
        {
            return View();
        }

        // POST: Product/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdProCreate(PRODUCT product)
        {
            if (ModelState.IsValid)
            {
                db.PRODUCTs.Add(product);
                db.SaveChanges();
                return RedirectToAction("AdProIndex");
            }
            return View(product);
        }

        // GET: Product/Edit/5
        public ActionResult AdProEdit(int id)
        {
            var product = db.PRODUCTs.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Product/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdProEdit(PRODUCT product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("AdProIndex");
            }
            return View(product);
        }

        // GET: Product/Delete/5
        public ActionResult AdProDelete(int id)
        {
            var product = db.PRODUCTs.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("AdProDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var product = db.PRODUCTs.Find(id);
            if (product != null)
            {
                db.PRODUCTs.Remove(product);
                db.SaveChanges();
            }
            return RedirectToAction("AdProIndex");
        }

        
        
    }
}

K22CNT4-TTCD-Nguyễn Văn Hiếu-2210900102/Controllers/MEMBERsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using K22CNT4_TTCD_Nguyễn_Văn_Hiếu_2210900102.Models;

namespace K22CNT4_TTCD_Nguyễn_Văn_Hiếu_2210900102.Controllers
{
    public class MEMBERsController : Controller
    {
        private QLCHEntities1 db = new QLCHEntities1();

        // GET: MEMBERs
        public ActionResult Index()
        {
            return View(db.MEMBERs.ToList());
        }

        // GET: MEMBERs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MEMBER mEMBER = db.MEMBERs.Find(id);
            if (mEMBER == null)
            {
                return HttpNotFound();
            }
            return View(mEMBER);
        }

        // GET: MEMBERs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MEMBERs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "member_id,member_name,member_username,member_pass,dia_chi,member_phone,member_email,ngay_sinh,ngay_cap_nhap,gioi_tinh,tich_diem")] MEMBER mEMBER)
        {
            if (ModelState.IsValid)
            {
                db.MEMBERs.Add(mEMBER);
                db.SaveChanges();
                return RedirectToAction("Login", "Account");
            }

            return View(mEMBER);
        }

        // GET: MEMBERs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MEMBER mEMBER = db.MEMBERs.Find(id);
            if (mEMBER == null)
            {
                return HttpNotFound();
            }
            return View(mEMBER);
        }

        // POST: MEMBERs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "member_id,member_name,member_username,member_pass,dia_chi,member_phone,member_email,ngay_sinh,ngay_cap_nhap,gioi_tinh,tich_diem")] MEMBER mEMBER)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mEMBER).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mEMBER);
        }

        // GET: MEMBERs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MEMBER mEMBER = db.MEMBERs.Find(id);
            if (mEMBER == null)
            {
                return HttpNotFound();
            }
            return View(mEMBER);
        }

        // POST: MEMBERs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MEMBER mEMBER = db.MEMBERs.Find(id);
            db.MEMBERs.Remove(mEMBER);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

K22CNT4-TTCD-Nguyễn Văn Hiếu-2210900102/Controllers/ORDERsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using K22CNT4_TTCD_Nguyễn_Văn_Hiếu_2210900102.Models;

namespace K22CNT4_TTCD_Nguyễn_Văn_Hiếu_2210900102.Controllers
{
    public class ORDERsController : Controller
    {
        private QLCHEntities1 db = new QLCHEntities1();

        // GET: ORDERs
        public ActionResult Index()
        {
            var oRDERS = db.ORDERS.Include(o => o.MEMBER);
            return View(oRDERS.ToList());
        }

        // GET: ORDERs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ORDER oRDER = db.ORDERS.Find(id);
            if (oRDER == null)
            {
                return HttpNotFound();
            }
            return View(oRDER);
        }

        // GET: ORDERs/Create
        public ActionResult Create()
        {
            ViewBag.member_id = new SelectList(db.MEMBERs, "member_id", "member_name");
            return View();
        }

        // POST: ORDERs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "order_id,order_date,order_status,product_price,total_price,member_id,quantity")] ORDER oRDER)
        {
            if (ModelState.IsValid)
            {
                db.ORDERS.Add(oRDER);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.member_id = new SelectList(db.MEMBERs, "member_id", "member_name", oRDER.member_id);
            return View(oRDER);
        }

        // GET: ORDERs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ORDER oRDER = db.ORDERS.Find(id);
            if (oRDER == null)
            {
                return HttpNotFound();
            }
            ViewBag.member_id = new SelectList(db.MEMBERs, "member_id", "member_name", oRDER.member_id);
            return View(oRDER);
        }

        // POST: ORDERs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "order_id,order_date,order_status,product_price,total_price,member_id,quantity")] ORDER oRDER)
        {
            if (ModelState.IsValid)
            {
                db.Entry(oRDER).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.member_id = new SelectList(db.MEMBERs, "member_id", "member_name", oRDER.member_id);
            return View(oRDER);
        }

        // GET: ORDERs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ORDER oRDER = db.ORDERS.Find(id);
            if (oRDER == null)
            {
                return HttpNotFound();
            }
            return View(oRDER);
        }

        // POST: ORDERs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ORDER oRDER = db.ORDERS.Find(id);
            db.ORDERS.Remove(oRDER);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

K22CNT4-TTCD-Nguyễn Văn Hiếu-2210900102/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jewelry Store - @ViewData["Title"]</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        /* Custom styles for navbar */
        .navbar {
            background-color: #ff6f61; /* Màu nền navbar */
        }

        .navbar-brand {
            font-weight: bold;
            color: #fff !important;
        }

        .navbar-nav .nav-link {
            margin-right: 20px;
            color: #fff !important;
        }

            .navbar-nav .nav-link:hover {
                color: #ffd700 !important; /* Màu vàng khi hover */
            }

        /* Dropdown menu */
        .dropdown-menu {
            background-color: #ff6f61;
            color: #fff;
        }

            .dropdown-menu .dropdown-item {
                color: #fff;
            }

                .dropdown-menu .dropdown-item:hover {
                    background-color: #ffd700;
                }

        /* Footer styles */
        footer {
            margin-top: 40px;
            padding: 20px;
            background-color: #343a40; /* Màu nền footer */
            color: #fff;
        }

            footer a {
                color: #ffd700;
                text-decoration: none;
            }

                footer a:hover {
                    color: #fff;
                }

        /* Custom button styles */
        .btn-outline-success {
            color: #fff;
            border-color: #ffd700;
        }

            .btn-outline-success:hover {
                background-color: #ffd700;
                border-color: #ffd700;
            }

        /* Custom styles for main content */
        .container {
            background-color: #f9f9f9;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
        }

        /* Badge style for cart */
        .cart-badge {
            background-color: #ffd700;
            color: #343a40;
            font-weight: bold;
            margin-left: 5px;
            padding: 2px 8px;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">Trang sức Whit</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="@Url.Action("Index", "Home")">Trang chủ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("AdProIndex", "Admin")">Quản lý sản phẩm</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Admin")">Quản lý Admin </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "MEMBERs")">Quản lý Member </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "ORDERs")">Quản lý Đơn hàng </a>
                    </li>



                    <!-- Kiểm tra trạng thái đăng nhập của người dùng -->
                    @if (Session["Account"] != null || Session["AdminAccount"] != null)
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Logout", "Account")">Đăng xuất</a>
                        </li>
                        <li class="nav-item">
                            <!-- Thêm biểu tượng người dùng -->
                            <a class="nav-link" href="@(Session["AdminAccount"] != null ? Url.Action("Index", "Admin") : Url.Action("AccountDetails", "Account"))">
                                <i class="fas fa-user"></i>
                            </a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Login", "Account")">Đăng nhập</a>
                        </li>
                    }
                </ul>
                <!-- Thanh tìm kiếm -->
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <!-- Main Content Section -->
    <div class="container mt-4">
        @RenderBody()
    </div>

    <!-- Footer -->
    <footer class="text-center">
        <p>&copy; 2024 Jewelry Store. All rights reserved.</p>
        <div>
            <a href="#">Facebook</a> | <a href="#">Instagram</a> | <a href="#">Twitter</a> <!-- Thêm liên kết mạng xã hội -->
        </div>
    </footer>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

K22CNT4-TTCD-Nguyễn Văn Hiếu-2210900102/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jewelry Store - @ViewData["Title"]</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        /* Custom styles for navbar */
        .navbar {
            background-color: #ff6f61; /* Màu nền navbar */
        }

        .navbar-brand {
            font-weight: bold;
            color: #fff !important;
        }

        .navbar-nav .nav-link {
            margin-right: 20px;
            color: #fff !important;
        }

            .navbar-nav .nav-link:hover {
                color: #ffd700 !important; /* Màu vàng khi hover */
            }

        /* Dropdown menu */
        .dropdown-menu {
            background-color: #ff6f61;
            color: #fff;
        }

            .dropdown-menu .dropdown-item {
                color: #fff;
            }

                .dropdown-menu .dropdown-item:hover {
                    background-color: #ffd700;
                }

        /* Footer styles */
        footer {
            margin-top: 40px;
            padding: 20px;
            background-color: #343a40; /* Màu nền footer */
            color: #fff;
        }

            footer a {
                color: #ffd700;
                text-decoration: none;
            }

                footer a:hover {
                    color: #fff;
                }

        /* Custom button styles */
        .btn-outline-success {
            color: #fff;
            border-color: #ffd700;
        }

            .btn-outline-success:hover {
                background-color: #ffd700;
                border-color: #ffd700;
            }

        /* Custom styles for main content */
        .container {
            background-color: #f9f9f9;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
        }

        /* Badge style for cart */
        .cart-badge {
            background-color: #ffd700;
            color: #343a40;
            font-weight: bold;
            margin-left: 5px;
            padding: 2px 8px;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">Trang sức Whit</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="@Url.Action("Index", "Home")">Trang chủ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("ProIndex", "PRODUCTs")">Sản phẩm</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Nhãn hiệu
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("About", "Home")">Giới thiệu</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Contact", "Home")">Liên hệ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Cart")">
                            Giỏ hàng
                        </a> <!-- Thêm số lượng giỏ hàng nếu cần -->
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Tutorial", "Home")">Hướng dẫn</a>
                    </li>

                    <!-- Kiểm tra trạng thái đăng nhập của người dùng -->
                    @if (Session["Account"] != null || Session["AdminAccount"] != null)
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Logout", "Account")">Đăng xuất</a>
                        </li>
                        <li class="nav-item">
                            <!-- Thêm biểu tượng người dùng -->
                            <a class="nav-link" href="@(Session["AdminAccount"] != null ? Url.Action("Index", "Admin") : Url.Action("AccountDetails", "Account"))">
                                <i class="fas fa-user"></i>
                            </a>
                        </li>
 }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Login", "Account")">Đăng nhập</a>
                        </li>
                    }
                </ul>
                <!-- Thanh tìm kiếm -->
                <form class="d-flex mb-4" role="search" action="/PRODUCTs/Search" method="GET">
                    <input class="form-control me-2" type="search" placeholder="Nhập tên sản phẩm" aria-label="Search" name="query" value="@Request.QueryString["query"]">
                    <button class="btn btn-outline-success" type="submit">Tìm kiếm</button>
                </form>

                <script>
                    function validateSearch() {
                        const searchInput = document.getElementById("searchInput").value.trim();

                        if (!searchInput) {
                            alert("Vui lòng nhập từ khóa để tìm kiếm.");
                            return false;
                        }
                        return true;
                    }
                </script>

                <style>
                    .form-control {
                        width: 300px; /* Chiều rộng của ô nhập */
                    }

                    .btn-success {
                        background-color: #28a745; /* Thay đổi màu sắc nút */
                        color: #fff;
                    }

                        .btn-success:hover {
                            background-color: #218838; /* Màu khi di chuột vào nút */
                        }
                </style>

            </div>
        </div>
    </nav>

    <!-- Main Content Section -->
    <div class="container mt-4">
        @RenderBody()
    </div>

    <!-- Footer -->
    <footer class="text-center">
        <p>&copy; 2024 Jewelry Store. All rights reserved.</p>
        <div>
            <a href="#">Facebook</a> | <a href="#">Instagram</a> | <a href="#">Twitter</a> <!-- Thêm liên kết mạng xã hội -->
        </div>
    </footer>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>